# Generated by Django 4.1.5 on 2023-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employement',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
