# Generated by Django 4.1.5 on 2023-04-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
